### ISSUE TITLE
bamcheck errors with hardclipped reads

### ISSUE THREAD

**Issue by jts** [VertebrateResequencing/vr-codebase#46]
`bamcheck.c:count_mismatches_per_cycle` will segfault with some hardclipped reads.

The problem is that the read length is calculated from the query sequence field (`bam_line->core.l_qseq`) which is the hardclipped length while the `icycle` variable properly accounts for the hardclipped bases. Therefore, when idx is calculated:

```
int idx = is_fwd ? icycle : read_len-icycle-1;
```

`read_len-icycle` can be negative. Here is a small example record to demonstrate the problem:

```
test_read   2163    test_ref    417 1   264H36M =   1866    1654    GTATAACGAACTCTCTGAAGTGGTTCAGTCTATGCC    FF8F8EGGGGFFDEF@7<<EGF6<FGGDFF@A6<CC    NM:i:1  AS:i:31 XS:i:27
```

In this case `read_len=36` whereas `icycle>=264`.

The solution is to infer the original read length directly from the CIGAR string.

This problem also exists in `count_indels`.

**Comment by pd3** [comment]
Closing with the same comment as #47
